services:
  localhost:
    image: alpine:latest
    command: sleep infinity
    ports:
      - "8080:8080" # backend port
      - "8180:8180" # oauth-sample port
      - "5173:5173"
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    network_mode: "service:localhost"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_HTTP_PORT: 8180
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./customers_realm-export.json:/opt/keycloak/data/import/customers_realm-export.json

  backend:
    build: ./customers_backend
    container_name: customers_backend
    network_mode: "service:localhost"
    depends_on:
      - keycloak

  frontend:
    build: ./customers_frontend
    container_name: customers_frontend
    network_mode: "service:localhost"
    command: npm run preview -- --port 5173 --host
    depends_on:
      - backend